// config.js
module.exports = {
  JWT_SECRET: 'your_jwt_secret',
  WS_TOKEN_SECRET: 'your_ws_token_secret',
  
  permisosProfesional: [
    'ver_pacientes',
    'crear_pacientes',
    'modificar_pacientes',
    'ver_turnos',
    'crear_turnos',
    'modificar_turnos',
    'eliminar_turnos',
    'crear_bloqueos',
    'modificar_bloqueos',
    'eliminar_bloqueos', 
    'ver_bloqueos', 
    'ver_profesionales',
    'ver_usuarios',
    'editar_usuarios',
    'ver_agenda',
    'modificar_profesionales'
  ],
  permisos : [
    'ver_turnos',
    'crear_turnos',
    'modificar_turnos',
    'eliminar_turnos',
    'crear_bloqueos',
    'modificar_bloqueos',
    'eliminar_bloqueos', 
    'ver_bloqueos', 
    'ver_profesionales',
    'eliminar_profesionales',
    'crear_profesionales',
    'modificar_profesionales',
    'ver_pacientes',
    'modificar_pacientes',
    'crear_pacientes',
    'eliminar_pacientes',
    'ver_usuarios',
    'administrar_usuarios',
    'editar_usuarios',
    'ver_agenda'
  ],
  permisosSecretaria : [
    'ver_turnos',
    'crear_turnos',
    'modificar_turnos',
    'eliminar_turnos',
    'crear_bloqueos',
    'modificar_bloqueos',
    'eliminar_bloqueos', 
    'ver_bloqueos', 
    'ver_profesionales',
    'eliminar_profesionales',
    'crear_profesionales',
    'modificar_profesionales',
    'ver_pacientes',
    'modificar_pacientes',
    'crear_pacientes',
    'eliminar_pacientes',
    'ver_agenda',
    'ver_usuarios',
    'editar_usuarios',
  ] 
};
